//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopOnline.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public string OrderID { get; set; }
        public int CusID { get; set; }
        public string BillID { get; set; }
        public System.DateTime DateOrder { get; set; }
        public string Stt { get; set; }
    
        public virtual Bill Bill { get; set; }
        public virtual Customer Customer { get; set; }
    }
}
